O Numpy é um pacote que fornece um objeto de matriz multidimensional, vários objetos derivados e e uma variedade de rotinas para operações rápidas em matrizes, incluindo matemática, lógica, manipulação de forma, classificação, seleção, E/S , transformadas discretas de Fourier, álgebra linear básica, operações estatísticas básicas, simulação aleatória e muito mais.

Pacote mais importante para processamento numérico em python. 

In [1]:
import numpy as np

In [4]:
km = np.loadtxt('carros-km.txt') #carrega o arquivo de texto carros-km.txt

In [6]:
km

array([4.44100e+04, 5.71200e+03, 3.71230e+04, 0.00000e+00, 2.57570e+04,
       1.07280e+04, 0.00000e+00, 7.75990e+04, 9.91970e+04, 3.79780e+04,
       1.28590e+04, 8.05200e+03, 8.97730e+04, 0.00000e+00, 4.14570e+04,
       1.15607e+05, 4.64490e+04, 0.00000e+00, 3.70860e+04, 1.51730e+04,
       1.01193e+05, 0.00000e+00, 9.80790e+04, 1.02959e+05, 0.00000e+00,
       0.00000e+00, 5.79500e+03, 0.00000e+00, 5.88480e+04, 9.43810e+04,
       3.01630e+04, 5.33320e+04, 1.77200e+04, 3.38080e+04, 9.06840e+04,
       4.39750e+04, 0.00000e+00, 0.00000e+00, 5.52600e+03, 0.00000e+00,
       9.34150e+04, 4.07620e+04, 0.00000e+00, 8.63020e+04, 0.00000e+00,
       9.75500e+03, 6.99450e+04, 2.39500e+03, 0.00000e+00, 8.03490e+04,
       8.55540e+04, 5.04960e+04, 6.77160e+04, 9.39470e+04, 3.53450e+04,
       8.10070e+04, 1.19513e+05, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 1.18895e+05, 4.85090e+04, 1.00912e+05,
       9.56490e+04, 0.00000e+00, 9.04950e+04, 0.00000e+00, 2.913

In [7]:
anos = np.loadtxt('carros-anos.txt', dtype = int) #define um array a partir de dados externos

In [8]:
anos

array([2003, 1991, 1990, 2019, 2006, 2012, 2019, 2009, 2010, 2011, 2002,
       2007, 2001, 2019, 2009, 2016, 2012, 2019, 2016, 2017, 2002, 2019,
       1994, 1991, 2019, 2019, 2016, 2019, 2002, 1991, 1997, 1995, 2018,
       1991, 2014, 1995, 2019, 2019, 2009, 2019, 2013, 2003, 2019, 2002,
       2019, 2002, 2004, 2001, 2019, 2003, 2009, 2006, 2000, 2006, 2010,
       1994, 2007, 2019, 2019, 2019, 2019, 2019, 2017, 2011, 2001, 1996,
       2019, 1994, 2019, 2007, 1994, 2007, 1997, 2006, 2013, 1994, 2008,
       2008, 2019, 2019, 1999, 2007, 1993, 1995, 2019, 2019, 2016, 2011,
       2019, 2002, 2013, 2017, 2016, 2008, 2018, 2003, 2003, 2004, 2010,
       2019, 2006, 2001, 2019, 2015, 2018, 2017, 1992, 2001, 1993, 1995,
       2003, 2014, 2008, 2013, 2019, 2017, 2019, 2019, 2006, 2015, 2007,
       2005, 2017, 1998, 2019, 1999, 2019, 2009, 2003, 1994, 2019, 1994,
       2019, 2015, 1996, 1997, 1993, 2019, 1992, 1995, 2019, 1990, 2019,
       2019, 1991, 1990, 2012, 2007, 2013, 2000, 20

In [9]:
#Obtendo a quilometragem média por ano:
km_mediana = km / (2023 - anos)

In [10]:
km_mediana

array([2.22050000e+03, 1.78500000e+02, 1.12493939e+03, 0.00000000e+00,
       1.51511765e+03, 9.75272727e+02, 0.00000000e+00, 5.54278571e+03,
       7.63053846e+03, 3.16483333e+03, 6.12333333e+02, 5.03250000e+02,
       4.08059091e+03, 0.00000000e+00, 2.96121429e+03, 1.65152857e+04,
       4.22263636e+03, 0.00000000e+00, 5.29800000e+03, 2.52883333e+03,
       4.81871429e+03, 0.00000000e+00, 3.38203448e+03, 3.21746875e+03,
       0.00000000e+00, 0.00000000e+00, 8.27857143e+02, 0.00000000e+00,
       2.80228571e+03, 2.94940625e+03, 1.16011538e+03, 1.90471429e+03,
       3.54400000e+03, 1.05650000e+03, 1.00760000e+04, 1.57053571e+03,
       0.00000000e+00, 0.00000000e+00, 3.94714286e+02, 0.00000000e+00,
       9.34150000e+03, 2.03810000e+03, 0.00000000e+00, 4.10961905e+03,
       0.00000000e+00, 4.64523810e+02, 3.68131579e+03, 1.08863636e+02,
       0.00000000e+00, 4.01745000e+03, 6.11100000e+03, 2.97035294e+03,
       2.94417391e+03, 5.52629412e+03, 2.71884615e+03, 2.79334483e+03,
      

In [11]:
np.arange(10) #Retorna valores uniformemente espaçados dentro de um determinado intervalo em um array. Nesse caso, os valores retornados estarão entre 0 e 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
kmm = np.array([1, 2, 3, 4, 5, 6, 7, 8]) #cria um array a partir de uma lista

In [13]:
kmm

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
type(kmm) #o tipo é um array numpy

numpy.ndarray

In [15]:
kmm.dtype #o dtype define o tipo do array de saída. Se o dtype não é informado, infere o tipo de dados dos outros argumentos de entrada

dtype('int32')

In [16]:
np.arange(7, dtype = "float")

array([0., 1., 2., 3., 4., 5., 6.])

In [17]:
quilometro = np.loadtxt("carros-km.txt", dtype=float)

In [18]:
quilometro

array([4.44100e+04, 5.71200e+03, 3.71230e+04, 0.00000e+00, 2.57570e+04,
       1.07280e+04, 0.00000e+00, 7.75990e+04, 9.91970e+04, 3.79780e+04,
       1.28590e+04, 8.05200e+03, 8.97730e+04, 0.00000e+00, 4.14570e+04,
       1.15607e+05, 4.64490e+04, 0.00000e+00, 3.70860e+04, 1.51730e+04,
       1.01193e+05, 0.00000e+00, 9.80790e+04, 1.02959e+05, 0.00000e+00,
       0.00000e+00, 5.79500e+03, 0.00000e+00, 5.88480e+04, 9.43810e+04,
       3.01630e+04, 5.33320e+04, 1.77200e+04, 3.38080e+04, 9.06840e+04,
       4.39750e+04, 0.00000e+00, 0.00000e+00, 5.52600e+03, 0.00000e+00,
       9.34150e+04, 4.07620e+04, 0.00000e+00, 8.63020e+04, 0.00000e+00,
       9.75500e+03, 6.99450e+04, 2.39500e+03, 0.00000e+00, 8.03490e+04,
       8.55540e+04, 5.04960e+04, 6.77160e+04, 9.39470e+04, 3.53450e+04,
       8.10070e+04, 1.19513e+05, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 1.18895e+05, 4.85090e+04, 1.00912e+05,
       9.56490e+04, 0.00000e+00, 9.04950e+04, 0.00000e+00, 2.913

In [19]:
quilometro.shape #mostra a dimensão, como é unidimensional mostra a quantidade de elementos nessa dimensão (única coluna)

(258,)

In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr
arr.shape #nesse caso mostro que o array tem duas dimensões e em cada dimensão possui 3 elementos

(2, 3)

In [21]:
#Comparando desempenho do ndarray com lista
np_array = np.arange(1000000)
py_list = list(range(1000000))
%time for _ in range (100): np_array *= 2
%time for _ in range(100): py_list = [ x * 2 for x in py_list]

CPU times: total: 78.1 ms
Wall time: 151 ms
CPU times: total: 15.5 s
Wall time: 26.1 s


<h5>Operações aritméticas em um array numpy sempre vão retornar um outro array, diferentemente de operações sobre listas, que para esse tipo, é necessário utilizar um laço de repetição, de forma a operar de forma iterativa cada um dos elementos da lista. Veja a diferença a seguir, de como calcular a idade de um carro (ano atual - ano de fabricação) em uma lista e em um array numpy.</h5>

In [22]:
#Para listas
carros_anos = [2003, 1991, 1990, 2019, 2006] 
#A seguinte operação: ano atual - carros_ano não é válida, veja
    #2023 - carros_anos
#Nesse caso, acontece um erro de unsupported operand type(s) for -: 'int' and 'list'isso porque não é possível calcular um valor inteiro com uma lista,
#Para isso, eu preciso criar um for que acesse cada um dos elementos indíce por indíce
for i in range (len(carros_anos)):
    idade_carros = (2023 - carros_anos[i])
    print(idade_carros)

20
32
33
4
17


In [23]:
#Em arrays numpy, basta:
carros_anos_np = np.array([2003, 1991, 1990, 2019, 2006]) 
idade_carro = 2023 - carros_anos_np
idade_carro

array([20, 32, 33,  4, 17])

<h3>Um array de numpy pode conter multi dimensões e pode simbolizar uma lista que irá conter uma quantidade n de listas dentro. Portanto, assume-se a seguinte analogia para ndarray multidimensional:</h3>

<ul>lista_1 = ([lista_a], [lista_b], [lista_c]) -> array_1 = np.array([lista_a], [lista_b], [lista_c])</ul>

<h5>Então, vamos praticar! </h5>

In [24]:
km_carros = [44410, 5712, 37123, 77599, 25757] #lista 1
carros_anos = [2003, 1991, 1990, 2019, 2006]  #lista 2

dados_carros = np.array([km_carros, carros_anos]) #criei um array de duas dimensões em que cada dimensão contém uma lista
print(dados_carros) #imprimindo o array multidimensional
dados_carros.shape #indica a dimensionalidade do array


[[44410  5712 37123 77599 25757]
 [ 2003  1991  1990  2019  2006]]


(2, 5)

In [25]:
#Para acessar os elementos do array
print(dados_carros[0]) #resulta na primeira linha inteira 
print(dados_carros[1])  #resulta na segunda linha inteira
print(dados_carros[0][1]) #nessa notação de matriz, eu indico qual a linha e também qual a coluna que eu desejo acessar e, portanto, apresenta o único elemento na linha 0 e coluna 1
print(dados_carros[1][3]) #outro exemplo de como acessar linha e coluna do ndarray
print(dados_carros[1, 3]) #além de utilizar a notação ndarray[linha][coluna] é possível utilizar ndarray[linha, coluna]

[44410  5712 37123 77599 25757]
[2003 1991 1990 2019 2006]
5712
2019
2019


<h1>Fatiamentos:</h1>
<ul>A sintaxe para realizar fatiamento em um array Numpy é i:j:k onde i é o índice inicial, j é o índice de para e k é o indicador de passo (interação) onde k != 0
Vamos para a prática</ul>

In [26]:
contador = np.arange(10)
contador
print(contador[1:4]) #ou seja, eu indiquei que eu quero o fatiamento da segunda posição (índice 1) para a terceira posição (índice 4) e como não indiquei o passo, k += 1
print(contador[1:8:2]) #da segunda posição à sétima, mas "pulando" de 2 em 2
print(contador[::2]) #os dois pontos apenas indica que irei começar no índice 0 até o índice final (10) e pulando de 2 em 2 (números pares de 0 a 10)
print(contador[1::2]) #números ímpares de 0 a 10

[1 2 3]
[1 3 5 7]
[0 2 4 6 8]
[1 3 5 7 9]


In [27]:
print(dados_carros)
print(dados_carros[:, 2]) #selecionei ambas as linhas do ndarray e apenas a coluna 2
print(dados_carros[:,4]) #selecionei ambas as linhas do ndarray e apenas a coluna 2
print(dados_carros[:, 1:3]) #fatiei na linha 1 das colunas 1 a 3

[[44410  5712 37123 77599 25757]
 [ 2003  1991  1990  2019  2006]]
[37123  1990]
[25757  2006]
[[ 5712 37123]
 [ 1991  1990]]


In [28]:
dados_carros[1] > 2000 #mostra os carros fabricados depois do ano 2000

array([ True, False, False,  True,  True])

Atributos numpy

In [29]:
carros_anos_np.shape 
#retorna a dimensionalidade do ndarray, em que o primeiro elemento refere-se ao número de linhas e o segundo, o número de colunas

(5,)

In [30]:
np.zeros(2)
#np.zeros retorna um novo array preenchida com zeros
#ela na verdade é formada por 3 atributos: np.zeros(shape, dtype, order) onde dtype e order são opcionais
#no caso do dtype não fornecido na função, por padrão, define os elementos como float

array([0., 0.])

In [31]:
np.zeros(3, dtype = int)
#veja que é possível alterar o tipo do array de zeros

array([0, 0, 0])

In [32]:
np.zeros((2,3))
#assim como também é possível alterar a dimensionalidade, onde o primeiro 2 indica o número de linhas
#e o segundo o número de elementos em cada linha

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.zeros((2,), dtype=[('x', 'i4'), ('y', 'i4')])
#além disso, podemos modificar o tipo da tupla

array([(0, 0), (0, 0)], dtype=[('x', '<i4'), ('y', '<i4')])

In [34]:
np.ones((2, 3, 4), dtype = int) 
#nesse caso, ele altera todos os elementos para 1 ao invés de 0

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [35]:
y = np.ones((1, 3, 4))
y.ndim
#o método ndim retorna o número de dimensões da matriz

3

In [36]:
y.size
#o método size retorna o número de elementos da matriz

12

In [37]:
print(dados_carros)
dados_carros.T

#retorna um array com os eixos transpostos. Logo, o que é coluna vira linha e o que é linha vira coluna
#Para uma matriz de uma única dimensão, isso retorna a matriz inalterada pois um vetor transposto é simplesmente o mesmo vetor
print("\n")
print(carros_anos_np)
carros_anos_np.T

[[44410  5712 37123 77599 25757]
 [ 2003  1991  1990  2019  2006]]


[2003 1991 1990 2019 2006]


array([2003, 1991, 1990, 2019, 2006])

In [38]:
print(dados_carros.tolist()) #transforma o ndarray em uma lista
dados_carros.dtype

[[44410, 5712, 37123, 77599, 25757], [2003, 1991, 1990, 2019, 2006]]


dtype('int32')

In [39]:
contador = np.arange(10)
contador
contador.reshape((5,2)) #o reshape da uma nova forma a matriz sem alterar os dados

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [40]:
km_carros = [44410, 5712, 37123, 77599, 25757] #lista 1
carros_anos = [2003, 1991, 1990, 2019, 2006]  #lista 2

info_carros = km_carros + carros_anos #vira uma lista muito difícil de se trabalhar
cars = np.array((info_carros)) 
#cars #mesmo criando um ndarray de info_carros, ainda sim ficaria melhor se fosse uma tupla
carros = cars.reshape((2, 5))
carros #nesse caso modificamos para uma matriz de 2 linhas e 5 colunas



array([[44410,  5712, 37123, 77599, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [41]:
dados_carros

array([[44410,  5712, 37123, 77599, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [42]:
dados_carros.resize((3,5), refcheck=False)
#Retorna uma nova matriz com a forma especificada.
#nesse caso, a matriz terá uma terceira linha com 5 elementos
dados_carros

array([[44410,  5712, 37123, 77599, 25757],
       [ 2003,  1991,  1990,  2019,  2006],
       [    0,     0,     0,     0,     0]])

<h1> Estatísticas com Numpy </h1>

In [43]:
anos = np.loadtxt('carros-anos.txt', dtype = int)
km = np.loadtxt('carros-km.txt')
valor = np.loadtxt('carros-valor.txt')

In [44]:
data_set = np.column_stack((anos, km, valor)) 
data_set
#o método column_stack faz a união de matrizes diferentes em uma única matriz, onde cada coluna é uma matriz diferente

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0190000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0190000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0190000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0190000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

In [45]:
print(anos.shape)
print(km.shape)
print(valor.shape)
print(data_set.shape) 
#nesse caso o data_set é resultado da únião de anos + km + valor, logo ele possui 258 linhas em 3 colunas

(258,)
(258,)
(258,)
(258, 3)


In [46]:
print(data_set.mean(),"\n") #nesse caso ele realiza a média de todas as linhas e todas as colunas
print(data_set.mean(axis=0),"\n") #aqui, indicando axis = 0, ele realiza a média de cada coluna, ou seja a média de anos, km e valor
print(data_set.mean(axis=1),"\n") #realiza a média de cada linha

48489.14648578811 

[ 2007.51162791 44499.41472868 98960.51310078] 

[44830.54666667 37954.98       37315.05333333 42189.35666667
 40125.03333333 36745.91       19488.06666667 63972.81333333
 73974.42333333 38851.83       28836.19666667 27992.84333333
 68168.99666667 18400.79333333 56984.80666667 59177.8
 36526.53       30190.46333333 33932.89666667 39638.76666667
 69780.79333333 32194.46666667 77867.61333333 76878.21666667
 41205.07       24462.03333333 34386.25       35817.28
 39298.42333333 72268.23333333 34289.06666667 41477.39333333
 26365.56333333 33918.13333333 50905.01       54959.84
 17875.19666667 41766.95666667 25768.39333333 34876.18
 54475.06333333 59333.43       29553.44666667 75040.79666667
 39881.91       22655.23333333 52057.21666667 31725.88333333
 22240.03333333 69567.49666667 78571.96333333 61600.27666667
 69114.54333333 58791.90333333 31242.99666667 51282.34333333
 83404.74333333 45116.06333333 44660.14333333 38017.42333333
 27806.11666667 33060.7        62306.3866

In [47]:
print(np.std(data_set[:,2]))
#aqui calcula o desvio padrão de todas as linhas da coluna 2, ou seja o desvio padrão da última coluna inteira
print(np.std(data_set[:,1]))
#aqui calcula o desvio padrão de todas as linhas da coluna 1, ou seja o desvio padrão da pnultima coluna inteira


29754.101150388564
39859.82699005149


In [48]:
print(data_set.sum()) #soma todos os elementos do vetor
print(data_set.sum(axis=0)) #realiza o somatório de cada uma das colunas
print(data_set.sum(axis=1)) #realiza o somatório de cada uma das linhas
print(data_set[:,1].sum()) #realiza o somatório apenas da segunda coluna (index 1)

37530599.379999995
[  517938.         11480849.         25531812.37999999]
[134491.64 113864.94 111945.16 126568.07 120375.1  110237.73  58464.2
 191918.44 221923.27 116555.49  86508.59  83978.53 204506.99  55202.38
 170954.42 177533.4  109579.59  90571.39 101798.69 118916.3  209342.38
  96583.4  233602.84 230634.65 123615.21  73386.1  103158.75 107451.84
 117895.27 216804.7  102867.2  124432.18  79096.69 101754.4  152715.03
 164879.52  53625.59 125300.87  77305.18 104628.54 163425.19 178000.29
  88660.34 225122.39 119645.73  67965.7  156171.65  95177.65  66720.1
 208702.49 235715.89 184800.83 207343.63 176375.71  93728.99 153847.03
 250214.23 135348.19 133980.43 114052.27  83418.35  99182.1  186919.16
 179296.22 245536.02 234575.13  68545.61 206643.87 144411.75 177855.91
 148281.68 184950.03 134675.49 112171.04 124178.23 181043.92 207169.86
 118899.21 147216.7   52761.1   87919.53 135946.87 145124.45 108306.5
  66526.72 117094.59 252760.6  257487.86 102399.28 128882.04 219483.84
 2394